---
- hosts: f5

  tasks:
          - name: Save the running configuration of the BIG-IP
            bigip_config:
                    reset: yes
                    server: lb.mydomain.com
                    password: secret
                    user: admin
                    validate_certs: no
            delegate_to: localhost
