---
- name: example_standard/Setup syslog
  bigip_remote_syslog:
    remote_host: 192.168.123.214
    server: "{{ bigip_ip }}"
    user: "{{ bigip_username }}"
    password: "{{ bigip_password }}"
    validate_certs: "{{ validate_certs }}"
  delegate_to: localhost

- name: example_standard/Set NTP server
  bigip_device_ntp:
    ntp_servers:
      - 192.0.2.23
    server: "{{ bigip_ip }}"
    user: "{{ bigip_username }}"
    password: "{{ bigip_password }}"
    validate_certs: "{{ validate_certs }}"
  delegate_to: localhost

- name: example_standard/Set timezone
  bigip_device_ntp:
    timezone: Etc/UTC
    server: "{{ bigip_ip }}"
    user: "{{ bigip_username }}"
    password: "{{ bigip_password }}"
    validate_certs: "{{ validate_certs }}"
  delegate_to: localhost

- name: example_standard/Set the DNS settings on the BIG-IP
  bigip_device_dns:
    name_servers:
      - 8.8.8.8
      - 8.8.4.4
    search:
      - example.local
    server: "{{ bigip_ip }}"
    user: "{{ bigip_username }}"
    password: "{{ bigip_password }}"
    validate_certs: "{{ validate_certs }}"
  delegate_to: localhost


#- name: example_standard/Save the config
  #bigip_config:
    #save: yes
    #server: "{{ bigip_ip }}"
    #user: "{{ bigip_username }}"
    #password: "{{ bigip_password }}"
    #validate_certs: "{{ validate_certs }}"
  #delegate_to: localhost
